# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'VGSShowDemoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VGSShowDemoApp

  pod 'VGSCollectSDK', '1.18.1'
  pod 'VGSShowSDK', :path => "../"


end
